controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster :
      type : joint_state_broadcaster/JointStateBroadcaster


    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      # left_wheel: left_wheel_joint
      # right_wheel: right_wheel_joint
      # publish_rate: 50.0
      # wheel_separation: 0.5
      # wheel_radius: 0.1
      # cmd_vel_timeout: 0.5
      # enable_odom_tf: true
      # odom_frame_id: odom
      # base_frame_id: base_link

    arm_joints_controller:
      type: forward_command_controller/ForwardCommandController


diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    # publish_rate: 50.0
    wheel_separation: 0.39
    wheel_radius: 0.05
    # cmd_vel_timeout: 0.5
    # enable_odom_tf: true
    odom_frame_id: "odom"
    base_frame_id: "base_link"

    pose_covariance_diagonal: [0.001,0.001,0.001,0.001,0.001,0.01]
    twist_covariance_diagonal: [0.001,0.001,0.001,0.001,0.001,0.01]

    publish_rate: 50.0
    enable_odom_tf: true

    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0

arm_joints_controller:
  ros__parameters:
    joints: ["arm_joint1", "arm_joint2"]
    interface_name: "position"